"""Receiving and storing uploaded photos, safely.

Two jobs, both security-shaped.

**Parsing multipart.** No framework, so the body is parsed here. It is a
boundary-delimited format and about sixty lines; the risk is reading an
unbounded body into memory, so the size cap is checked before the read rather
than after.

**Storing something a stranger sent.** The published copy is:

  - validated by MAGIC BYTES, never by filename or the Content-Type the client
    claims. An "image" that is really SVG or HTML executes as script on our own
    origin the moment a browser opens it — stored XSS wearing a photo's name.
  - renamed to a random id with an extension we chose. A filename from a
    client is an attacker-controlled path.
  - stripped of all metadata (see core/media.py) so publishing a photo does
    not publish where the photographer lives.
  - served with a fixed Content-Type and `nosniff`, so a browser cannot be
    talked into reinterpreting it.
"""

from __future__ import annotations

import re
import secrets
from pathlib import Path

from .media import ALLOWED, MAX_IMAGE_BYTES, BadImage, sniff, strip_metadata

UPLOAD_DIR = Path(__file__).resolve().parent.parent / "data" / "uploads"

EXTENSIONS = {"image/jpeg": ".jpg", "image/png": ".png"}

# Only ever generated by us, never taken from a client.
SAFE_NAME = re.compile(r"^[a-f0-9]{16}\.(jpg|png)$")


class TooLarge(ValueError):
    pass


def parse_multipart(body: bytes, content_type: str) -> dict:
    """Return {field_name: bytes|str} from a multipart/form-data body.

    Files come back as bytes, plain fields as str. Deliberately minimal: this
    form has a handful of short text fields and one image.
    """
    match = re.search(r'boundary=(?:"([^"]+)"|([^;]+))', content_type or "")
    if not match:
        raise ValueError("not a multipart body")
    boundary = (match.group(1) or match.group(2)).strip().encode()

    parts = body.split(b"--" + boundary)
    fields: dict = {}

    for part in parts:
        part = part.strip(b"\r\n")
        if not part or part == b"--":
            continue
        head, _, payload = part.partition(b"\r\n\r\n")
        if not _:
            continue

        headers = head.decode("utf-8", "replace")
        name_match = re.search(r'name="([^"]*)"', headers)
        if not name_match:
            continue
        name = name_match.group(1)

        payload = payload.rstrip(b"\r\n")
        if "filename=" in headers:
            if payload:
                fields[name] = payload
        else:
            fields[name] = payload.decode("utf-8", "replace").strip()

    return fields


def store_image(data: bytes, directory: Path | None = None) -> dict:
    """Validate, strip and save. Returns {url, bytes, stripped, content_type}.

    Raises BadImage for anything that is not a real JPEG or PNG.
    """
    if len(data) > MAX_IMAGE_BYTES:
        raise TooLarge(
            f"that image is {len(data) // (1024 * 1024)} MB — the limit is "
            f"{MAX_IMAGE_BYTES // (1024 * 1024)} MB")

    content_type = sniff(data)          # magic bytes, raises if not an image
    cleaned = strip_metadata(data)
    stripped = len(cleaned) != len(data)

    directory = directory or UPLOAD_DIR
    directory.mkdir(parents=True, exist_ok=True)

    name = secrets.token_hex(8) + EXTENSIONS[content_type]
    (directory / name).write_bytes(cleaned)

    return {
        "url": f"/uploads/{name}",
        "name": name,
        "bytes": len(cleaned),
        "stripped": stripped,
        "content_type": content_type,
    }


def resolve(name: str, directory: Path | None = None) -> tuple[Path, str] | None:
    """Map a request path to a stored file, or None.

    Pattern-matched against names we generate, so there is nothing to traverse
    with — a request for `../../etc/passwd` fails the regex before it ever
    touches the filesystem.
    """
    if not SAFE_NAME.match(name or ""):
        return None
    directory = directory or UPLOAD_DIR
    path = directory / name
    if not path.is_file():
        return None
    return path, ("image/png" if name.endswith(".png") else "image/jpeg")


__all__ = ["ALLOWED", "BadImage", "TooLarge", "parse_multipart", "resolve",
           "store_image", "UPLOAD_DIR"]
